### ISSUE TITLE
CHECK IT

### ISSUE THREAD

**Issue by maiorano84** [joeHarbulak/palindromeFunction#1]
https://github.com/maiorano84/palindromeFunction/tree/mmaiorano

**Comment by maiorano84** [comment]
[http://wiki.c2.com/?FizzBuzzTest](FizzBuzz)

**Comment by maiorano84** [comment]
https://laravel.com/docs/5.5/valet

**Comment by maiorano84** [comment]
https://xdebug.org/

**Comment by maiorano84** [comment]
https://www.facebook.com/maiorano84

**Comment by mattwinwood** [comment]
You're the man!
